apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring  #for prometheus to pick it up
    app.kubernetes.io/instance: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - fastapi
  selector:
    matchLabels:
      app: fastapi-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s